name: Compile Server

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: cmake
      run: cmake .

    - name: make
      run: make

    - name: Upload server binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux
        path: advancedserver/AdvancedServer
